# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(699, 495)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabProcInfo = QtGui.QWidget()
        self.tabProcInfo.setObjectName(_fromUtf8("tabProcInfo"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabProcInfo)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(self.tabProcInfo)
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setLineWidth(0)
        self.label.setMidLineWidth(0)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lbStage = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbStage.setFont(font)
        self.lbStage.setObjectName(_fromUtf8("lbStage"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbStage)
        self.label_9 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_3 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_13 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_12 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lbHeaterPower = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbHeaterPower.setFont(font)
        self.lbHeaterPower.setObjectName(_fromUtf8("lbHeaterPower"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.lbHeaterPower)
        self.label_8 = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lbNextStage = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbNextStage.setFont(font)
        self.lbNextStage.setObjectName(_fromUtf8("lbNextStage"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lbNextStage)
        self.lbStatus = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbStatus.setFont(font)
        self.lbStatus.setObjectName(_fromUtf8("lbStatus"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lbStatus)
        self.lbStageTimeElapsed = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbStageTimeElapsed.setFont(font)
        self.lbStageTimeElapsed.setObjectName(_fromUtf8("lbStageTimeElapsed"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lbStageTimeElapsed)
        self.lbTimerTimeElapsed = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbTimerTimeElapsed.setFont(font)
        self.lbTimerTimeElapsed.setObjectName(_fromUtf8("lbTimerTimeElapsed"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lbTimerTimeElapsed)
        self.lbTimerTimeRemaining = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbTimerTimeRemaining.setFont(font)
        self.lbTimerTimeRemaining.setObjectName(_fromUtf8("lbTimerTimeRemaining"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lbTimerTimeRemaining)
        self.lbTemp = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbTemp.setFont(font)
        self.lbTemp.setObjectName(_fromUtf8("lbTemp"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.lbTemp)
        self.lbSetPoint = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbSetPoint.setFont(font)
        self.lbSetPoint.setObjectName(_fromUtf8("lbSetPoint"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.lbSetPoint)
        self.lbPumpPower = QtGui.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbPumpPower.setFont(font)
        self.lbPumpPower.setObjectName(_fromUtf8("lbPumpPower"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.lbPumpPower)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tabProcInfo, _fromUtf8(""))
        self.tabStages = QtGui.QWidget()
        self.tabStages.setObjectName(_fromUtf8("tabStages"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabStages)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btAdd = QtGui.QToolButton(self.tabStages)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btAdd.setIcon(icon)
        self.btAdd.setObjectName(_fromUtf8("btAdd"))
        self.horizontalLayout_2.addWidget(self.btAdd)
        self.btRemove = QtGui.QToolButton(self.tabStages)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/del.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btRemove.setIcon(icon1)
        self.btRemove.setObjectName(_fromUtf8("btRemove"))
        self.horizontalLayout_2.addWidget(self.btRemove)
        self.btSave = QtGui.QToolButton(self.tabStages)
        self.btSave.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btSave.setIcon(icon2)
        self.btSave.setObjectName(_fromUtf8("btSave"))
        self.horizontalLayout_2.addWidget(self.btSave)
        self.btLoad = QtGui.QToolButton(self.tabStages)
        self.btLoad.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/load.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btLoad.setIcon(icon3)
        self.btLoad.setObjectName(_fromUtf8("btLoad"))
        self.horizontalLayout_2.addWidget(self.btLoad)
        self.btStart = QtGui.QToolButton(self.tabStages)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btStart.setIcon(icon4)
        self.btStart.setObjectName(_fromUtf8("btStart"))
        self.horizontalLayout_2.addWidget(self.btStart)
        self.btStop = QtGui.QToolButton(self.tabStages)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/Icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btStop.setIcon(icon5)
        self.btStop.setObjectName(_fromUtf8("btStop"))
        self.horizontalLayout_2.addWidget(self.btStop)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView_Stages = QtGui.QTableView(self.tabStages)
        self.tableView_Stages.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView_Stages.setObjectName(_fromUtf8("tableView_Stages"))
        self.verticalLayout.addWidget(self.tableView_Stages)
        self.tabWidget.addTab(self.tabStages, _fromUtf8(""))
        self.tabComponents = QtGui.QWidget()
        self.tabComponents.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabComponents.sizePolicy().hasHeightForWidth())
        self.tabComponents.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabComponents.setFont(font)
        self.tabComponents.setObjectName(_fromUtf8("tabComponents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabComponents)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.grpPID = QtGui.QGroupBox(self.tabComponents)
        self.grpPID.setMaximumSize(QtCore.QSize(16777215, 250))
        self.grpPID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grpPID.setFlat(False)
        self.grpPID.setCheckable(False)
        self.grpPID.setObjectName(_fromUtf8("grpPID"))
        self.gridLayout = QtGui.QGridLayout(self.grpPID)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pLabel = QtGui.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pLabel.setFont(font)
        self.pLabel.setTextFormat(QtCore.Qt.PlainText)
        self.pLabel.setObjectName(_fromUtf8("pLabel"))
        self.gridLayout.addWidget(self.pLabel, 1, 0, 1, 1)
        self.iLabel = QtGui.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.iLabel.setFont(font)
        self.iLabel.setObjectName(_fromUtf8("iLabel"))
        self.gridLayout.addWidget(self.iLabel, 2, 0, 1, 1)
        self.dLabel = QtGui.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dLabel.setFont(font)
        self.dLabel.setObjectName(_fromUtf8("dLabel"))
        self.gridLayout.addWidget(self.dLabel, 3, 0, 1, 1)
        self.setPointLabel = QtGui.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.setPointLabel.setFont(font)
        self.setPointLabel.setObjectName(_fromUtf8("setPointLabel"))
        self.gridLayout.addWidget(self.setPointLabel, 4, 0, 1, 1)
        self.outLabel = QtGui.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outLabel.setFont(font)
        self.outLabel.setObjectName(_fromUtf8("outLabel"))
        self.gridLayout.addWidget(self.outLabel, 5, 0, 1, 1)
        self.currentTempCLabel = QtGui.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.currentTempCLabel.setFont(font)
        self.currentTempCLabel.setObjectName(_fromUtf8("currentTempCLabel"))
        self.gridLayout.addWidget(self.currentTempCLabel, 7, 0, 1, 1)
        self.labelTemp = QtGui.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(True)
        self.labelTemp.setFont(font)
        self.labelTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp.setObjectName(_fromUtf8("labelTemp"))
        self.gridLayout.addWidget(self.labelTemp, 7, 1, 1, 1)
        self.PField = QtGui.QDoubleSpinBox(self.grpPID)
        self.PField.setMaximum(1000.0)
        self.PField.setObjectName(_fromUtf8("PField"))
        self.gridLayout.addWidget(self.PField, 1, 1, 1, 1)
        self.IField = QtGui.QDoubleSpinBox(self.grpPID)
        self.IField.setMaximum(1000.0)
        self.IField.setObjectName(_fromUtf8("IField"))
        self.gridLayout.addWidget(self.IField, 2, 1, 1, 1)
        self.DField = QtGui.QDoubleSpinBox(self.grpPID)
        self.DField.setMaximum(1000.0)
        self.DField.setObjectName(_fromUtf8("DField"))
        self.gridLayout.addWidget(self.DField, 3, 1, 1, 1)
        self.SPField = QtGui.QDoubleSpinBox(self.grpPID)
        self.SPField.setMaximum(100.0)
        self.SPField.setObjectName(_fromUtf8("SPField"))
        self.gridLayout.addWidget(self.SPField, 4, 1, 1, 1)
        self.ChkPidEnabled = QtGui.QCheckBox(self.grpPID)
        self.ChkPidEnabled.setObjectName(_fromUtf8("ChkPidEnabled"))
        self.gridLayout.addWidget(self.ChkPidEnabled, 0, 0, 1, 1)
        self.sliderOutPower = QtGui.QSlider(self.grpPID)
        self.sliderOutPower.setMaximum(100)
        self.sliderOutPower.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOutPower.setObjectName(_fromUtf8("sliderOutPower"))
        self.gridLayout.addWidget(self.sliderOutPower, 5, 1, 1, 1)
        self.labelOutPower = QtGui.QLabel(self.grpPID)
        self.labelOutPower.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutPower.setObjectName(_fromUtf8("labelOutPower"))
        self.gridLayout.addWidget(self.labelOutPower, 6, 1, 1, 1)
        self.horizontalLayout.addWidget(self.grpPID)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.grpBomb = QtGui.QGroupBox(self.tabComponents)
        self.grpBomb.setMaximumSize(QtCore.QSize(16777215, 80))
        self.grpBomb.setObjectName(_fromUtf8("grpBomb"))
        self.formLayout_2 = QtGui.QFormLayout(self.grpBomb)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.enabledLabel = QtGui.QLabel(self.grpBomb)
        self.enabledLabel.setObjectName(_fromUtf8("enabledLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.enabledLabel)
        self.chkPumpEnabled = QtGui.QCheckBox(self.grpBomb)
        self.chkPumpEnabled.setChecked(True)
        self.chkPumpEnabled.setObjectName(_fromUtf8("chkPumpEnabled"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.chkPumpEnabled)
        self.powerLabel = QtGui.QLabel(self.grpBomb)
        self.powerLabel.setObjectName(_fromUtf8("powerLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.powerLabel)
        self.sliderPumpPower = QtGui.QSlider(self.grpBomb)
        self.sliderPumpPower.setMaximum(255)
        self.sliderPumpPower.setProperty("value", 80)
        self.sliderPumpPower.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPumpPower.setObjectName(_fromUtf8("sliderPumpPower"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sliderPumpPower)
        self.verticalLayout_3.addWidget(self.grpBomb)
        self.grpTimer = QtGui.QGroupBox(self.tabComponents)
        self.grpTimer.setObjectName(_fromUtf8("grpTimer"))
        self.formLayout = QtGui.QFormLayout(self.grpTimer)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbcondtemp = QtGui.QLabel(self.grpTimer)
        self.lbcondtemp.setObjectName(_fromUtf8("lbcondtemp"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbcondtemp)
        self.cbTimerStartCond = QtGui.QComboBox(self.grpTimer)
        self.cbTimerStartCond.setObjectName(_fromUtf8("cbTimerStartCond"))
        self.cbTimerStartCond.addItem(_fromUtf8(""))
        self.cbTimerStartCond.addItem(_fromUtf8(""))
        self.cbTimerStartCond.addItem(_fromUtf8(""))
        self.cbTimerStartCond.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbTimerStartCond)
        self.lbtemp = QtGui.QLabel(self.grpTimer)
        self.lbtemp.setObjectName(_fromUtf8("lbtemp"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbtemp)
        self.timerTempField = QtGui.QDoubleSpinBox(self.grpTimer)
        self.timerTempField.setObjectName(_fromUtf8("timerTempField"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.timerTempField)
        self.lbtime = QtGui.QLabel(self.grpTimer)
        self.lbtime.setObjectName(_fromUtf8("lbtime"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbtime)
        self.timerTimeField = QtGui.QTimeEdit(self.grpTimer)
        self.timerTimeField.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.timerTimeField.setObjectName(_fromUtf8("timerTimeField"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.timerTimeField)
        self.verticalLayout_3.addWidget(self.grpTimer)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabComponents, _fromUtf8(""))
        self.tabIngridients = QtGui.QWidget()
        self.tabIngridients.setObjectName(_fromUtf8("tabIngridients"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabIngridients)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btAdd_2 = QtGui.QToolButton(self.tabIngridients)
        self.btAdd_2.setText(_fromUtf8(""))
        self.btAdd_2.setIcon(icon)
        self.btAdd_2.setObjectName(_fromUtf8("btAdd_2"))
        self.horizontalLayout_3.addWidget(self.btAdd_2)
        self.btRemove_2 = QtGui.QToolButton(self.tabIngridients)
        self.btRemove_2.setText(_fromUtf8(""))
        self.btRemove_2.setIcon(icon1)
        self.btRemove_2.setObjectName(_fromUtf8("btRemove_2"))
        self.horizontalLayout_3.addWidget(self.btRemove_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tableView_Ingridients = QtGui.QTableView(self.tabIngridients)
        self.tableView_Ingridients.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView_Ingridients.setObjectName(_fromUtf8("tableView_Ingridients"))
        self.verticalLayout_4.addWidget(self.tableView_Ingridients)
        self.tabWidget.addTab(self.tabIngridients, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionIniciar = QtGui.QAction(MainWindow)
        self.actionIniciar.setObjectName(_fromUtf8("actionIniciar"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.cbTimerStartCond.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Beer Controller", None))
        self.label.setText(_translate("MainWindow", "Etapa", None))
        self.lbStage.setText(_translate("MainWindow", "Desconhecida", None))
        self.label_9.setText(_translate("MainWindow", "Próxima etapa", None))
        self.label_3.setText(_translate("MainWindow", "Estado", None))
        self.label_4.setText(_translate("MainWindow", "Tempo decorrido", None))
        self.label_5.setText(_translate("MainWindow", "Tempo de timer", None))
        self.label_6.setText(_translate("MainWindow", "Tempo restante", None))
        self.label_7.setText(_translate("MainWindow", "Temperatura atual", None))
        self.label_13.setText(_translate("MainWindow", "Set Point", None))
        self.label_12.setText(_translate("MainWindow", "Potência aquec.", None))
        self.lbHeaterPower.setText(_translate("MainWindow", "0%", None))
        self.label_8.setText(_translate("MainWindow", "Potência bomba", None))
        self.lbNextStage.setText(_translate("MainWindow", "Nenhuma", None))
        self.lbStatus.setText(_translate("MainWindow", "Aguardando inicio", None))
        self.lbStageTimeElapsed.setText(_translate("MainWindow", "00:00:00", None))
        self.lbTimerTimeElapsed.setText(_translate("MainWindow", "00:00:00", None))
        self.lbTimerTimeRemaining.setText(_translate("MainWindow", "00:00:00", None))
        self.lbTemp.setText(_translate("MainWindow", "0º", None))
        self.lbSetPoint.setText(_translate("MainWindow", "0º", None))
        self.lbPumpPower.setText(_translate("MainWindow", "0%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProcInfo), _translate("MainWindow", "Informações do processo", None))
        self.btAdd.setText(_translate("MainWindow", "Adicionar", None))
        self.btRemove.setText(_translate("MainWindow", "...", None))
        self.btStart.setText(_translate("MainWindow", "...", None))
        self.btStop.setText(_translate("MainWindow", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStages), _translate("MainWindow", "Etapas", None))
        self.grpPID.setTitle(_translate("MainWindow", "PID", None))
        self.pLabel.setText(_translate("MainWindow", "P:", None))
        self.iLabel.setText(_translate("MainWindow", "I:", None))
        self.dLabel.setText(_translate("MainWindow", "D:", None))
        self.setPointLabel.setText(_translate("MainWindow", "SetPoint (ºC)", None))
        self.outLabel.setText(_translate("MainWindow", "Output Power: ", None))
        self.currentTempCLabel.setText(_translate("MainWindow", "Current Temp.", None))
        self.labelTemp.setText(_translate("MainWindow", "0º", None))
        self.ChkPidEnabled.setText(_translate("MainWindow", "Enabled", None))
        self.labelOutPower.setText(_translate("MainWindow", "0%", None))
        self.grpBomb.setTitle(_translate("MainWindow", "Bomba", None))
        self.enabledLabel.setText(_translate("MainWindow", "Enabled", None))
        self.powerLabel.setText(_translate("MainWindow", "Power (%): ", None))
        self.grpTimer.setTitle(_translate("MainWindow", "Temporizador", None))
        self.lbcondtemp.setText(_translate("MainWindow", "Condição inicio", None))
        self.cbTimerStartCond.setItemText(0, _translate("MainWindow", "Desativado", None))
        self.cbTimerStartCond.setItemText(1, _translate("MainWindow", "No inicio do estagio", None))
        self.cbTimerStartCond.setItemText(2, _translate("MainWindow", "Temperatura maior/igual a", None))
        self.cbTimerStartCond.setItemText(3, _translate("MainWindow", "Temperatura menor/igual a", None))
        self.lbtemp.setText(_translate("MainWindow", "Temperatura da cond.", None))
        self.lbtime.setText(_translate("MainWindow", "Tempo", None))
        self.timerTimeField.setDisplayFormat(_translate("MainWindow", "HH:mm:ss", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabComponents), _translate("MainWindow", "Componentes do Sistema", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIngridients), _translate("MainWindow", "Ingredientes", None))
        self.actionIniciar.setText(_translate("MainWindow", "Iniciar", None))

import resources_rc
