# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabProcInfo = QtWidgets.QWidget()
        self.tabProcInfo.setObjectName("tabProcInfo")
        self.tabProcInfoLay = QtWidgets.QHBoxLayout(self.tabProcInfo)
        self.tabProcInfoLay.setObjectName("tabProcInfoLay")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.tabProcInfo)
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(0)
        self.label.setMidLineWidth(0)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lbStage = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbStage.setFont(font)
        self.lbStage.setObjectName("lbStage")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbStage)
        self.label_9 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lbNextStage = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbNextStage.setFont(font)
        self.lbNextStage.setObjectName("lbNextStage")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbNextStage)
        self.label_3 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lbStatus = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbStatus.setFont(font)
        self.lbStatus.setObjectName("lbStatus")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbStatus)
        self.label_4 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lbStageTimeElapsed = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbStageTimeElapsed.setFont(font)
        self.lbStageTimeElapsed.setObjectName("lbStageTimeElapsed")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbStageTimeElapsed)
        self.label_5 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lbTimerTimeElapsed = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbTimerTimeElapsed.setFont(font)
        self.lbTimerTimeElapsed.setObjectName("lbTimerTimeElapsed")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbTimerTimeElapsed)
        self.label_6 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lbTimerTimeRemaining = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbTimerTimeRemaining.setFont(font)
        self.lbTimerTimeRemaining.setObjectName("lbTimerTimeRemaining")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbTimerTimeRemaining)
        self.label_7 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lbTemp = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbTemp.setFont(font)
        self.lbTemp.setObjectName("lbTemp")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lbTemp)
        self.label_13 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lbSetPoint = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbSetPoint.setFont(font)
        self.lbSetPoint.setObjectName("lbSetPoint")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lbSetPoint)
        self.label_12 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lbHeaterPower = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbHeaterPower.setFont(font)
        self.lbHeaterPower.setObjectName("lbHeaterPower")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lbHeaterPower)
        self.label_8 = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lbPumpPower = QtWidgets.QLabel(self.tabProcInfo)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbPumpPower.setFont(font)
        self.lbPumpPower.setObjectName("lbPumpPower")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lbPumpPower)
        self.tabProcInfoLay.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tabProcInfo, "")
        self.tabStages = QtWidgets.QWidget()
        self.tabStages.setObjectName("tabStages")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabStages)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btAdd = QtWidgets.QToolButton(self.tabStages)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btAdd.setIcon(icon)
        self.btAdd.setObjectName("btAdd")
        self.horizontalLayout_2.addWidget(self.btAdd)
        self.btRemove = QtWidgets.QToolButton(self.tabStages)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btRemove.setIcon(icon1)
        self.btRemove.setObjectName("btRemove")
        self.horizontalLayout_2.addWidget(self.btRemove)
        self.btSave = QtWidgets.QToolButton(self.tabStages)
        self.btSave.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btSave.setIcon(icon2)
        self.btSave.setObjectName("btSave")
        self.horizontalLayout_2.addWidget(self.btSave)
        self.btLoad = QtWidgets.QToolButton(self.tabStages)
        self.btLoad.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btLoad.setIcon(icon3)
        self.btLoad.setObjectName("btLoad")
        self.horizontalLayout_2.addWidget(self.btLoad)
        self.btStart = QtWidgets.QToolButton(self.tabStages)
        self.btStart.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btStart.setIcon(icon4)
        self.btStart.setObjectName("btStart")
        self.horizontalLayout_2.addWidget(self.btStart)
        self.btStop = QtWidgets.QToolButton(self.tabStages)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btStop.setIcon(icon5)
        self.btStop.setObjectName("btStop")
        self.horizontalLayout_2.addWidget(self.btStop)
        self.btPause = QtWidgets.QToolButton(self.tabStages)
        self.btPause.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btPause.setIcon(icon6)
        self.btPause.setObjectName("btPause")
        self.horizontalLayout_2.addWidget(self.btPause)
        self.btPrev = QtWidgets.QToolButton(self.tabStages)
        self.btPrev.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btPrev.setIcon(icon7)
        self.btPrev.setObjectName("btPrev")
        self.horizontalLayout_2.addWidget(self.btPrev)
        self.btNext = QtWidgets.QToolButton(self.tabStages)
        self.btNext.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btNext.setIcon(icon8)
        self.btNext.setObjectName("btNext")
        self.horizontalLayout_2.addWidget(self.btNext)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView_Stages = QtWidgets.QTableView(self.tabStages)
        self.tableView_Stages.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_Stages.setObjectName("tableView_Stages")
        self.verticalLayout.addWidget(self.tableView_Stages)
        self.tabWidget.addTab(self.tabStages, "")
        self.tabComponents = QtWidgets.QWidget()
        self.tabComponents.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabComponents.sizePolicy().hasHeightForWidth())
        self.tabComponents.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabComponents.setFont(font)
        self.tabComponents.setObjectName("tabComponents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabComponents)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grpPID = QtWidgets.QGroupBox(self.tabComponents)
        self.grpPID.setMaximumSize(QtCore.QSize(16777215, 250))
        self.grpPID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grpPID.setFlat(False)
        self.grpPID.setCheckable(False)
        self.grpPID.setObjectName("grpPID")
        self.gridLayout = QtWidgets.QGridLayout(self.grpPID)
        self.gridLayout.setObjectName("gridLayout")
        self.pLabel = QtWidgets.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pLabel.setFont(font)
        self.pLabel.setTextFormat(QtCore.Qt.PlainText)
        self.pLabel.setObjectName("pLabel")
        self.gridLayout.addWidget(self.pLabel, 1, 0, 1, 1)
        self.iLabel = QtWidgets.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.iLabel.setFont(font)
        self.iLabel.setObjectName("iLabel")
        self.gridLayout.addWidget(self.iLabel, 2, 0, 1, 1)
        self.dLabel = QtWidgets.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dLabel.setFont(font)
        self.dLabel.setObjectName("dLabel")
        self.gridLayout.addWidget(self.dLabel, 3, 0, 1, 1)
        self.setPointLabel = QtWidgets.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.setPointLabel.setFont(font)
        self.setPointLabel.setObjectName("setPointLabel")
        self.gridLayout.addWidget(self.setPointLabel, 4, 0, 1, 1)
        self.outLabel = QtWidgets.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outLabel.setFont(font)
        self.outLabel.setObjectName("outLabel")
        self.gridLayout.addWidget(self.outLabel, 5, 0, 1, 1)
        self.currentTempCLabel = QtWidgets.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.currentTempCLabel.setFont(font)
        self.currentTempCLabel.setObjectName("currentTempCLabel")
        self.gridLayout.addWidget(self.currentTempCLabel, 7, 0, 1, 1)
        self.labelTemp = QtWidgets.QLabel(self.grpPID)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(True)
        self.labelTemp.setFont(font)
        self.labelTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp.setObjectName("labelTemp")
        self.gridLayout.addWidget(self.labelTemp, 7, 1, 1, 1)
        self.PField = QtWidgets.QDoubleSpinBox(self.grpPID)
        self.PField.setMaximum(1000.0)
        self.PField.setObjectName("PField")
        self.gridLayout.addWidget(self.PField, 1, 1, 1, 1)
        self.IField = QtWidgets.QDoubleSpinBox(self.grpPID)
        self.IField.setMaximum(1000.0)
        self.IField.setObjectName("IField")
        self.gridLayout.addWidget(self.IField, 2, 1, 1, 1)
        self.DField = QtWidgets.QDoubleSpinBox(self.grpPID)
        self.DField.setMaximum(1000.0)
        self.DField.setObjectName("DField")
        self.gridLayout.addWidget(self.DField, 3, 1, 1, 1)
        self.SPField = QtWidgets.QDoubleSpinBox(self.grpPID)
        self.SPField.setMaximum(100.0)
        self.SPField.setObjectName("SPField")
        self.gridLayout.addWidget(self.SPField, 4, 1, 1, 1)
        self.ChkPidEnabled = QtWidgets.QCheckBox(self.grpPID)
        self.ChkPidEnabled.setObjectName("ChkPidEnabled")
        self.gridLayout.addWidget(self.ChkPidEnabled, 0, 0, 1, 1)
        self.sliderOutPower = QtWidgets.QSlider(self.grpPID)
        self.sliderOutPower.setMaximum(100)
        self.sliderOutPower.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOutPower.setObjectName("sliderOutPower")
        self.gridLayout.addWidget(self.sliderOutPower, 5, 1, 1, 1)
        self.labelOutPower = QtWidgets.QLabel(self.grpPID)
        self.labelOutPower.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutPower.setObjectName("labelOutPower")
        self.gridLayout.addWidget(self.labelOutPower, 6, 1, 1, 1)
        self.horizontalLayout.addWidget(self.grpPID)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grpBomb = QtWidgets.QGroupBox(self.tabComponents)
        self.grpBomb.setMaximumSize(QtCore.QSize(16777215, 80))
        self.grpBomb.setObjectName("grpBomb")
        self.formLayout_2 = QtWidgets.QFormLayout(self.grpBomb)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.enabledLabel = QtWidgets.QLabel(self.grpBomb)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.chkPumpEnabled = QtWidgets.QCheckBox(self.grpBomb)
        self.chkPumpEnabled.setChecked(True)
        self.chkPumpEnabled.setObjectName("chkPumpEnabled")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chkPumpEnabled)
        self.powerLabel = QtWidgets.QLabel(self.grpBomb)
        self.powerLabel.setObjectName("powerLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.powerLabel)
        self.sliderPumpPower = QtWidgets.QSlider(self.grpBomb)
        self.sliderPumpPower.setMaximum(255)
        self.sliderPumpPower.setProperty("value", 80)
        self.sliderPumpPower.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPumpPower.setObjectName("sliderPumpPower")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sliderPumpPower)
        self.verticalLayout_3.addWidget(self.grpBomb)
        self.grpTimer = QtWidgets.QGroupBox(self.tabComponents)
        self.grpTimer.setObjectName("grpTimer")
        self.formLayout = QtWidgets.QFormLayout(self.grpTimer)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lbcondtemp = QtWidgets.QLabel(self.grpTimer)
        self.lbcondtemp.setObjectName("lbcondtemp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbcondtemp)
        self.cbTimerStartCond = QtWidgets.QComboBox(self.grpTimer)
        self.cbTimerStartCond.setObjectName("cbTimerStartCond")
        self.cbTimerStartCond.addItem("")
        self.cbTimerStartCond.addItem("")
        self.cbTimerStartCond.addItem("")
        self.cbTimerStartCond.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbTimerStartCond)
        self.lbtemp = QtWidgets.QLabel(self.grpTimer)
        self.lbtemp.setObjectName("lbtemp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbtemp)
        self.timerTempField = QtWidgets.QDoubleSpinBox(self.grpTimer)
        self.timerTempField.setObjectName("timerTempField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timerTempField)
        self.lbtime = QtWidgets.QLabel(self.grpTimer)
        self.lbtime.setObjectName("lbtime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbtime)
        self.timerTimeField = QtWidgets.QTimeEdit(self.grpTimer)
        self.timerTimeField.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timerTimeField.setObjectName("timerTimeField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timerTimeField)
        self.verticalLayout_3.addWidget(self.grpTimer)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabComponents, "")
        self.tabPlot = QtWidgets.QWidget()
        self.tabPlot.setObjectName("tabPlot")
        self.tabPlotLay = QtWidgets.QVBoxLayout(self.tabPlot)
        self.tabPlotLay.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.tabPlotLay.setObjectName("tabPlotLay")
        self.groupBox = QtWidgets.QGroupBox(self.tabPlot)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16772715))
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plotPosScroll = QtWidgets.QScrollBar(self.groupBox)
        self.plotPosScroll.setMinimum(0)
        self.plotPosScroll.setMaximum(1)
        self.plotPosScroll.setProperty("value", 1)
        self.plotPosScroll.setOrientation(QtCore.Qt.Horizontal)
        self.plotPosScroll.setObjectName("plotPosScroll")
        self.verticalLayout_5.addWidget(self.plotPosScroll)
        self.chkAutoScroll = QtWidgets.QCheckBox(self.groupBox)
        self.chkAutoScroll.setObjectName("chkAutoScroll")
        self.verticalLayout_5.addWidget(self.chkAutoScroll)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.testLabel = QtWidgets.QLabel(self.groupBox)
        self.testLabel.setObjectName("testLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.testLabel)
        self.zoomSlider = QtWidgets.QSlider(self.groupBox)
        self.zoomSlider.setMinimum(0)
        self.zoomSlider.setMaximum(99)
        self.zoomSlider.setSingleStep(1)
        self.zoomSlider.setProperty("value", 1)
        self.zoomSlider.setSliderPosition(1)
        self.zoomSlider.setTracking(True)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setInvertedAppearance(False)
        self.zoomSlider.setInvertedControls(False)
        self.zoomSlider.setObjectName("zoomSlider")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zoomSlider)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setObjectName("formLayout_5")
        self.chkPumpLine = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkPumpLine.setObjectName("chkPumpLine")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.chkPumpLine)
        self.chkHeaterLine = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkHeaterLine.setObjectName("chkHeaterLine")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.chkHeaterLine)
        self.chkSensor1Line = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkSensor1Line.setObjectName("chkSensor1Line")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.chkSensor1Line)
        self.chkSensor2Line = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkSensor2Line.setObjectName("chkSensor2Line")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.chkSensor2Line)
        self.pushPumpColor = QtWidgets.QPushButton(self.groupBox_2)
        self.pushPumpColor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushPumpColor.sizePolicy().hasHeightForWidth())
        self.pushPumpColor.setSizePolicy(sizePolicy)
        self.pushPumpColor.setMinimumSize(QtCore.QSize(0, 0))
        self.pushPumpColor.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushPumpColor.setText("")
        self.pushPumpColor.setObjectName("pushPumpColor")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushPumpColor)
        self.pushHeaterColor = QtWidgets.QPushButton(self.groupBox_2)
        self.pushHeaterColor.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushHeaterColor.setText("")
        self.pushHeaterColor.setObjectName("pushHeaterColor")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushHeaterColor)
        self.pushSensor1Color = QtWidgets.QPushButton(self.groupBox_2)
        self.pushSensor1Color.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushSensor1Color.setText("")
        self.pushSensor1Color.setObjectName("pushSensor1Color")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushSensor1Color)
        self.pushSensor2Color = QtWidgets.QPushButton(self.groupBox_2)
        self.pushSensor2Color.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushSensor2Color.setText("")
        self.pushSensor2Color.setObjectName("pushSensor2Color")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushSensor2Color)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabPlotLay.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tabPlot, "")
        self.tabIngridients = QtWidgets.QWidget()
        self.tabIngridients.setObjectName("tabIngridients")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabIngridients)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btAdd_2 = QtWidgets.QToolButton(self.tabIngridients)
        self.btAdd_2.setText("")
        self.btAdd_2.setIcon(icon)
        self.btAdd_2.setObjectName("btAdd_2")
        self.horizontalLayout_3.addWidget(self.btAdd_2)
        self.btRemove_2 = QtWidgets.QToolButton(self.tabIngridients)
        self.btRemove_2.setText("")
        self.btRemove_2.setIcon(icon1)
        self.btRemove_2.setObjectName("btRemove_2")
        self.horizontalLayout_3.addWidget(self.btRemove_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tableView_Ingridients = QtWidgets.QTableView(self.tabIngridients)
        self.tableView_Ingridients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_Ingridients.setObjectName("tableView_Ingridients")
        self.verticalLayout_4.addWidget(self.tableView_Ingridients)
        self.tabWidget.addTab(self.tabIngridients, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIniciar = QtWidgets.QAction(MainWindow)
        self.actionIniciar.setObjectName("actionIniciar")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.cbTimerStartCond.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beer Controller"))
        self.label.setText(_translate("MainWindow", "Etapa"))
        self.lbStage.setText(_translate("MainWindow", "Desconhecida"))
        self.label_9.setText(_translate("MainWindow", "Próxima etapa"))
        self.lbNextStage.setText(_translate("MainWindow", "Nenhuma"))
        self.label_3.setText(_translate("MainWindow", "Estado"))
        self.lbStatus.setText(_translate("MainWindow", "Aguardando inicio"))
        self.label_4.setText(_translate("MainWindow", "Tempo decorrido"))
        self.lbStageTimeElapsed.setText(_translate("MainWindow", "00:00:00"))
        self.label_5.setText(_translate("MainWindow", "Tempo de timer"))
        self.lbTimerTimeElapsed.setText(_translate("MainWindow", "00:00:00"))
        self.label_6.setText(_translate("MainWindow", "Tempo restante"))
        self.lbTimerTimeRemaining.setText(_translate("MainWindow", "00:00:00"))
        self.label_7.setText(_translate("MainWindow", "Temperatura atual"))
        self.lbTemp.setText(_translate("MainWindow", "0º"))
        self.label_13.setText(_translate("MainWindow", "Set Point"))
        self.lbSetPoint.setText(_translate("MainWindow", "0º"))
        self.label_12.setText(_translate("MainWindow", "Potência aquec."))
        self.lbHeaterPower.setText(_translate("MainWindow", "0%"))
        self.label_8.setText(_translate("MainWindow", "Potência bomba"))
        self.lbPumpPower.setText(_translate("MainWindow", "0%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProcInfo), _translate("MainWindow", "Informações do processo"))
        self.btAdd.setText(_translate("MainWindow", "Adicionar"))
        self.btRemove.setText(_translate("MainWindow", "..."))
        self.btStop.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStages), _translate("MainWindow", "Etapas"))
        self.grpPID.setTitle(_translate("MainWindow", "PID"))
        self.pLabel.setText(_translate("MainWindow", "P:"))
        self.iLabel.setText(_translate("MainWindow", "I:"))
        self.dLabel.setText(_translate("MainWindow", "D:"))
        self.setPointLabel.setText(_translate("MainWindow", "SetPoint (ºC)"))
        self.outLabel.setText(_translate("MainWindow", "Output Power: "))
        self.currentTempCLabel.setText(_translate("MainWindow", "Current Temp."))
        self.labelTemp.setText(_translate("MainWindow", "0º"))
        self.ChkPidEnabled.setText(_translate("MainWindow", "Enabled"))
        self.labelOutPower.setText(_translate("MainWindow", "0%"))
        self.grpBomb.setTitle(_translate("MainWindow", "Bomba"))
        self.enabledLabel.setText(_translate("MainWindow", "Enabled"))
        self.powerLabel.setText(_translate("MainWindow", "Power (%): "))
        self.grpTimer.setTitle(_translate("MainWindow", "Temporizador"))
        self.lbcondtemp.setText(_translate("MainWindow", "Condição inicio"))
        self.cbTimerStartCond.setItemText(0, _translate("MainWindow", "Desativado"))
        self.cbTimerStartCond.setItemText(1, _translate("MainWindow", "No inicio do estagio"))
        self.cbTimerStartCond.setItemText(2, _translate("MainWindow", "Temperatura maior/igual a"))
        self.cbTimerStartCond.setItemText(3, _translate("MainWindow", "Temperatura menor/igual a"))
        self.lbtemp.setText(_translate("MainWindow", "Temperatura da cond."))
        self.lbtime.setText(_translate("MainWindow", "Tempo"))
        self.timerTimeField.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabComponents), _translate("MainWindow", "Componentes do Sistema"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.chkAutoScroll.setText(_translate("MainWindow", "Auto Scroll"))
        self.testLabel.setText(_translate("MainWindow", "Zoom"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.chkPumpLine.setText(_translate("MainWindow", "Potência da Bomba"))
        self.chkHeaterLine.setText(_translate("MainWindow", "Potência da Resistência"))
        self.chkSensor1Line.setText(_translate("MainWindow", "Senor 1 Temperatura"))
        self.chkSensor2Line.setText(_translate("MainWindow", "Sensor 2 Temperatura"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlot), _translate("MainWindow", "Gráfico"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIngridients), _translate("MainWindow", "Ingredientes"))
        self.actionIniciar.setText(_translate("MainWindow", "Iniciar"))
import resources_rc
